<?
error_reporting(E_ALL);
ini_set('display_errors', 1);

header('content-type: text/html; charset="UTF-8"');

ob_start(); ?>

<select name="city" id="city" value="835">
  <optgroup label="Адыгея Респ">
  <option value="23">Адыгейск</option>
  <option value="553">Майкоп</option>
  </optgroup>
  <optgroup label="Алтай Респ">
  <option value="226">Горно-Алтайск</option>
  </optgroup>
  <optgroup label="Алтайский край">
  <option value="41">Алейск</option>
  <option value="95">Барнаул</option>
  <option value="121">Белокуриха</option>
  <option value="64">Бийск</option>
  <option value="232">Горняк</option>
  <option value="326">Заринск</option>
  <option value="323">Змеиногорск</option>
  <option value="384">Камень-на-Оби</option>
  <option value="620">Новоалтайск</option>
  <option value="801">Рубцовск</option>
  <option value="915">Славгород</option>
  <option value="1109">Яровое</option>
  </optgroup>
  <optgroup label="Амурская обл">
  <option value="34287">21 Свободный</option>
  <option value="117">Белогорск</option>
  <option value="76">Благовещенск</option>
  <option value="34359">Бочкаревка</option>
  <option value="298">Завитинск</option>
  <option value="315">Зея</option>
  <option value="798">Райчихинск</option>
  <option value="859">Свободный</option>
  <option value="34358">Серышево-2</option>
  <option value="34357">Серышево-4</option>
  <option value="911">Сковородино</option>
  <option value="34360">Тавричанка</option>
  <option value="974">Тында</option>
  <option value="1066">Шимановск</option>
  </optgroup>
  <optgroup label="Архангельская обл">
  <option value="48">Архангельск</option>
  <option value="155">Вельск</option>
  <option value="414">Каргополь</option>
  <option value="397">Коряжма</option>
  <option value="409">Котлас</option>
  <option value="601">Мезень</option>
  <option value="566">Мирный</option>
  <option value="626">Новодвинск</option>
  <option value="690">Няндома</option>
  <option value="726">Онега</option>
  <option value="869">Северодвинск</option>
  <option value="844">Сольвычегодск</option>
  <option value="1062">Шенкурск</option>
  </optgroup>
  <optgroup label="Астраханская обл">
  <option value="54">Астрахань</option>
  <option value="58">Ахтубинск</option>
  <option value="325">Знаменск</option>
  <option value="388">Камызяк</option>
  <option value="627">Нариманов</option>
  <option value="1023">Харабали</option>
  </optgroup>
  <optgroup label="Башкортостан Респ">
  <option value="19">Агидель</option>
  <option value="73">Баймак</option>
  <option value="111">Белебей</option>
  <option value="125">Белорецк</option>
  <option value="72">Бирск</option>
  <option value="33785">Благовещенск</option>
  <option value="238">Давлеканово</option>
  <option value="269">Дюртюли</option>
  <option value="350">Ишимбай</option>
  <option value="479">Кумертау</option>
  <option value="597">Межгорье</option>
  <option value="1589">Межгорье-1</option>
  <option value="605">Мелеуз</option>
  <option value="659">Нефтекамск</option>
  <option value="712">Октябрьский</option>
  <option value="819">Салават</option>
  <option value="907">Сибай</option>
  <option value="890">Стерлитамак</option>
  <option value="962">Туймазы</option>
  <option value="1004">Уфа</option>
  <option value="1008">Учалы</option>
  <option value="1105">Янаул</option>
  </optgroup>
  <optgroup label="Белгородская обл">
  <option value="49">Алексеевка</option>
  <option value="109">Белгород</option>
  <option value="39890">Белгород-22</option>
  <option value="145">Валуйки</option>
  <option value="207">Грайворон</option>
  <option value="219">Губкин</option>
  <option value="393">Короча</option>
  <option value="40507">Новый Оскол</option>
  <option value="40859">Старый Оскол</option>
  <option value="41119">Строитель</option>
  <option value="1058">Шебекино</option>
  </optgroup>
  <optgroup label="Брянская обл">
  <option value="126">Брянск</option>
  <option value="271">Дятьково</option>
  <option value="295">Жуковка</option>
  <option value="321">Злынка</option>
  <option value="410">Карачев</option>
  <option value="492">Клинцы</option>
  <option value="587">Мглин</option>
  <option value="628">Новозыбков</option>
  <option value="746">Почеп</option>
  <option value="877">Севск</option>
  <option value="881">Сельцо</option>
  <option value="886">Стародуб</option>
  <option value="908">Сураж</option>
  <option value="956">Трубчевск</option>
  <option value="999">Унеча</option>
  <option value="41805">Фокино</option>
  </optgroup>
  <optgroup label="Бурятия Респ">
  <option value="65">Бабушкин</option>
  <option value="235">Гусиноозерск</option>
  <option value="310">Закаменск</option>
  <option value="509">Кяхта</option>
  <option value="867">Северобайкальск</option>
  <option value="995">Улан-Удэ</option>
  </optgroup>
  <optgroup label="Владимирская обл">
  <option value="43">Александров</option>
  <option value="197">Владимир</option>
  <option value="194">Вязники</option>
  <option value="203">Гороховец</option>
  <option value="237">Гусь-Хрустальный</option>
  <option value="386">Камешково</option>
  <option value="400">Карабаново</option>
  <option value="462">Киржач</option>
  <option value="500">Ковров</option>
  <option value="45525">Ковров-35</option>
  <option value="367">Кольчугино</option>
  <option value="399">Костерево</option>
  <option value="491">Курлово</option>
  <option value="518">Лакинск</option>
  <option value="603">Меленки</option>
  <option value="602">Муром</option>
  <option value="767">Петушки</option>
  <option value="793">Покров</option>
  <option value="794">Радужный</option>
  <option value="820">Собинка</option>
  <option value="894">Струнино</option>
  <option value="902">Судогда</option>
  <option value="904">Суздаль</option>
  <option value="1091">Юрьев-Польский</option>
  </optgroup>
  <optgroup label="Волгоградская обл">
  <option value="199">Волгоград</option>
  <option value="150">Волжский</option>
  <option value="263">Дубовка</option>
  <option value="291">Жирновск</option>
  <option value="360">Калач-на-Дону</option>
  <option value="390">Камышин</option>
  <option value="405">Котельниково</option>
  <option value="411">Котово</option>
  <option value="48256">Краснослободск</option>
  <option value="528">Ленинск</option>
  <option value="570">Михайловка</option>
  <option value="685">Николаевск</option>
  <option value="622">Новоаннинский</option>
  <option value="735">Палласовка</option>
  <option value="47386">Петров Вал</option>
  <option value="891">Серафимович</option>
  <option value="912">Суровикино</option>
  <option value="1009">Урюпинск</option>
  <option value="1012">Фролово</option>
  </optgroup>
  <optgroup label="Вологодская обл">
  <option value="63">Бабаево</option>
  <option value="119">Белозерск</option>
  <option value="50951">Великий Устюг</option>
  <option value="152">Вологда</option>
  <option value="188">Вытегра</option>
  <option value="215">Грязовец</option>
  <option value="352">Кадников</option>
  <option value="464">Кириллов</option>
  <option value="417">Красавино</option>
  <option value="689">Никольск</option>
  <option value="832">Сокол</option>
  <option value="950">Тотьма</option>
  <option value="1002">Устюжна</option>
  <option value="1025">Харовск</option>
  <option value="1053">Череповец</option>
  </optgroup>
  <optgroup label="Воронежская обл">
  <option value="82">Бобров</option>
  <option value="92">Богучар</option>
  <option value="114">Борисоглебск</option>
  <option value="142">Бутурлиновка</option>
  <option value="168">Воронеж</option>
  <option value="358">Калач</option>
  <option value="511">Лиски</option>
  <option value="624">Нововоронеж</option>
  <option value="660">Новохоперск</option>
  <option value="715">Острогожск</option>
  <option value="731">Павловск</option>
  <option value="785">Поворино</option>
  <option value="816">Россошь</option>
  <option value="885">Семилуки</option>
  <option value="1087">Эртиль</option>
  </optgroup>
  <optgroup label="Дагестан Респ">
  <option value="140">Буйнакск</option>
  <option value="6625">Дагестанские Огни</option>
  <option value="258">Дербент</option>
  <option value="343">Избербаш</option>
  <option value="424">Каспийск</option>
  <option value="444">Кизилюрт</option>
  <option value="446">Кизляр</option>
  <option value="585">Махачкала</option>
  <option value="1027">Хасавюрт</option>
  <option value="1096">Южно-Сухокумск</option>
  </optgroup>
  <optgroup label="Другие страны">
  <option value="179913">Япония</option>
  </optgroup>
  <optgroup label="Еврейская Аобл">
  <option value="70">Биробиджан</option>
  <option value="692">Облучье</option>
  </optgroup>
  <optgroup label="Ивановская обл">
  <option value="59790">14 Военный</option>
  <option value="191">Вичуга</option>
  <option value="60205">Гаврилов Посад</option>
  <option value="302">Заволжск</option>
  <option value="333">Иваново</option>
  <option value="456">Кинешма</option>
  <option value="60889">Комсомольск</option>
  <option value="415">Кохма</option>
  <option value="615">Наволоки</option>
  <option value="783">Плес</option>
  <option value="754">Приволжск</option>
  <option value="780">Пучеж</option>
  <option value="812">Родники</option>
  <option value="961">Тейково</option>
  <option value="1016">Фурманов</option>
  <option value="1076">Шуя</option>
  <option value="1092">Южа</option>
  <option value="1093">Юрьевец</option>
  </optgroup>
  <optgroup label="Ингушетия Респ">
  <option value="404">Карабулак</option>
  <option value="8266">Магас</option>
  <option value="565">Малгобек</option>
  <option value="621">Назрань</option>
  </optgroup>
  <optgroup label="Иркутская обл">
  <option value="53">Алзамай</option>
  <option value="12">Ангарск</option>
  <option value="71">Байкальск</option>
  <option value="74">Бирюсинск</option>
  <option value="94">Бодайбо</option>
  <option value="122">Братск</option>
  <option value="189">Вихоревка</option>
  <option value="63909">Железногорск-Илимский</option>
  <option value="317">Зима</option>
  <option value="340">Иркутск</option>
  <option value="460">Киренск</option>
  <option value="671">Нижнеудинск</option>
  <option value="847">Саянск</option>
  <option value="857">Свирск</option>
  <option value="925">Слюдянка</option>
  <option value="939">Тайшет</option>
  <option value="966">Тулун</option>
  <option value="988">Усолье-Сибирское</option>
  <option value="994">Усть-Илимск</option>
  <option value="998">Усть-Кут</option>
  <option value="1049">Черемхово</option>
  <option value="1060">Шелехов</option>
  </optgroup>
  <optgroup label="Кабардино-Балкарская Респ">
  <option value="77">Баксан</option>
  <option value="555">Майский</option>
  <option value="625">Нальчик</option>
  <option value="631">Нарткала</option>
  <option value="770">Прохладный</option>
  <option value="967">Терек</option>
  <option value="976">Тырныауз</option>
  <option value="8510">Чегем</option>
  </optgroup>
  <optgroup label="Калининградская обл">
  <option value="69">Багратионовск</option>
  <option value="91">Балтийск</option>
  <option value="214">Гвардейск</option>
  <option value="229">Гурьевск</option>
  <option value="233">Гусев</option>
  <option value="307">Зеленоградск</option>
  <option value="364">Калининград</option>
  <option value="433">Краснознаменск</option>
  <option value="516">Ладушкин</option>
  <option value="575">Мамоново</option>
  <option value="647">Неман</option>
  <option value="655">Нестеров</option>
  <option value="704">Озерск</option>
  <option value="775">Пионерский</option>
  <option value="732">Полесск</option>
  <option value="752">Правдинск</option>
  <option value="849">Светлогорск</option>
  <option value="853">Светлый</option>
  <option value="917">Славск</option>
  <option value="166474">Советск</option>
  <option value="1038">Черняховск</option>
  </optgroup>
  <optgroup label="Калмыкия Респ">
  <option value="201">Городовиковск</option>
  <option value="514">Лагань</option>
  <option value="1083">Элиста</option>
  </optgroup>
  <optgroup label="Калужская обл">
  <option value="79">Балабаново</option>
  <option value="66795">Балабаново-1</option>
  <option value="67470">Белоусово</option>
  <option value="118">Боровск</option>
  <option value="66799">Ермолино</option>
  <option value="289">Жиздра</option>
  <option value="293">Жуков</option>
  <option value="370">Калуга</option>
  <option value="468">Киров</option>
  <option value="508">Козельск</option>
  <option value="379">Кондрово</option>
  <option value="67471">Кременки</option>
  <option value="545">Людиново</option>
  <option value="571">Малоярославец</option>
  <option value="595">Медынь</option>
  <option value="550">Мещовск</option>
  <option value="592">Мосальск</option>
  <option value="694">Обнинск</option>
  <option value="854">Сосенский</option>
  <option value="866">Спас-Деменск</option>
  <option value="918">Сухиничи</option>
  <option value="951">Таруса</option>
  <option value="1097">Юхнов</option>
  </optgroup>
  <optgroup label="Камчатская обл">
  <option value="187">Вилючинск</option>
  <option value="283">Елизово</option>
  <option value="494">Ключи</option>
  <option value="69964">Ключи-1</option>
  <option value="763">Петропавловск-Камчатский</option>
  </optgroup>
  <optgroup label="Карачаево-Черкесская Респ">
  <option value="408">Карачаевск</option>
  <option value="8889">Сторожевая-2</option>
  <option value="959">Теберда</option>
  <option value="992">Усть-Джегута</option>
  <option value="1055">Черкесск</option>
  </optgroup>
  <optgroup label="Карелия Респ">
  <option value="123">Беломорск</option>
  <option value="10001">Больничный</option>
  <option value="440">Кемь</option>
  <option value="377">Кондопога</option>
  <option value="401">Костомукша</option>
  <option value="522">Лахденпохья</option>
  <option value="591">Медвежьегорск</option>
  <option value="718">Олонец</option>
  <option value="761">Петрозаводск</option>
  <option value="777">Питкяранта</option>
  <option value="776">Пудож</option>
  <option value="879">Сегежа</option>
  <option value="852">Сортавала</option>
  <option value="906">Суоярви</option>
  </optgroup>
  <optgroup label="Кемеровская обл">
  <option value="16">Анжеро-Судженск</option>
  <option value="115">Белово</option>
  <option value="139">Березовский</option>
  <option value="70268">Гурьевск</option>
  <option value="368">Калтан</option>
  <option value="438">Кемерово</option>
  <option value="484">Киселевск</option>
  <option value="530">Ленинск-Кузнецкий</option>
  <option value="579">Мариинск</option>
  <option value="599">Междуреченск</option>
  <option value="606">Мыски</option>
  <option value="632">Новокузнецк</option>
  <option value="707">Осинники</option>
  <option value="734">Полысаево</option>
  <option value="764">Прокопьевск</option>
  <option value="821">Салаир</option>
  <option value="937">Тайга</option>
  <option value="955">Таштагол</option>
  <option value="942">Топки</option>
  <option value="1089">Юрга</option>
  </optgroup>
  <optgroup label="Кировская обл">
  <option value="71846">Белая Холуница</option>
  <option value="72098">Вятские Поляны</option>
  <option value="329">Зуевка</option>
  <option value="71336">Киров</option>
  <option value="474">Кирово-Чепецк</option>
  <option value="480">Кирс</option>
  <option value="407">Котельнич</option>
  <option value="525">Луза</option>
  <option value="567">Малмыж</option>
  <option value="598">Мураши</option>
  <option value="674">Нолинск</option>
  <option value="724">Омутнинск</option>
  <option value="699">Орлов</option>
  <option value="923">Слободской</option>
  <option value="826">Советск</option>
  <option value="856">Сосновка</option>
  <option value="1005">Уржум</option>
  <option value="74475">Халтурин</option>
  <option value="1107">Яранск</option>
  </optgroup>
  <optgroup label="Коми Респ">
  <option value="166">Воркута</option>
  <option value="10729">ВОХР</option>
  <option value="178">Вуктыл</option>
  <option value="276">Емва</option>
  <option value="334">Инта</option>
  <option value="554">Микунь</option>
  <option value="769">Печора</option>
  <option value="862">Сосногорск</option>
  <option value="926">Сыктывкар</option>
  <option value="982">Усинск</option>
  <option value="1006">Ухта</option>
  </optgroup>
  <optgroup label="Костромская обл">
  <option value="138">Буй</option>
  <option value="146">Волгореченск</option>
  <option value="210">Галич</option>
  <option value="359">Кологрив</option>
  <option value="403">Кострома</option>
  <option value="559">Макарьев</option>
  <option value="577">Мантурово</option>
  <option value="649">Нерехта</option>
  <option value="665">Нея</option>
  <option value="836">Солигалич</option>
  <option value="1056">Чухлома</option>
  <option value="1065">Шарья</option>
  </optgroup>
  <optgroup label="Краснодарский край">
  <option value="17">Абинск</option>
  <option value="61">Анапа</option>
  <option value="24">Апшеронск</option>
  <option value="38">Армавир</option>
  <option value="127">Белореченск</option>
  <option value="218">Геленджик</option>
  <option value="27083">Горячий Ключ</option>
  <option value="227">Гулькевичи</option>
  <option value="275">Ейск</option>
  <option value="387">Кореновск</option>
  <option value="429">Краснодар</option>
  <option value="461">Кропоткин</option>
  <option value="463">Крымск</option>
  <option value="487">Курганинск</option>
  <option value="510">Лабинск</option>
  <option value="657">Нефтегорск</option>
  <option value="630">Новокубанск</option>
  <option value="644">Новороссийск</option>
  <option value="760">Приморско-Ахтарск</option>
  <option value="919">Славянск-на-Кубани</option>
  <option value="864">Сочи</option>
  <option value="965">Темрюк</option>
  <option value="971">Тимашевск</option>
  <option value="975">Тихорецк</option>
  <option value="960">Туапсе</option>
  <option value="1000">Усть-Лабинск</option>
  <option value="1019">Хадыженск</option>
  </optgroup>
  <optgroup label="Красноярский край">
  <option value="44">Артемовск</option>
  <option value="60">Ачинск</option>
  <option value="90">Боготол</option>
  <option value="120">Бородино</option>
  <option value="266">Дивногорск</option>
  <option value="278">Енисейск</option>
  <option value="81926">Железногорск</option>
  <option value="312">Заозерный</option>
  <option value="178531">Зеленогорск</option>
  <option value="339">Игарка</option>
  <option value="347">Иланский</option>
  <option value="356">Кайеркан</option>
  <option value="398">Канск</option>
  <option value="506">Кодинск</option>
  <option value="451">Красноярск</option>
  <option value="28986">Красноярск-26</option>
  <option value="29037">Красноярск-45</option>
  <option value="540">Лесосибирск</option>
  <option value="560">Минусинск</option>
  <option value="619">Назарово</option>
  <option value="676">Норильск</option>
  <option value="858">Сосновоборск</option>
  <option value="945">Талнах</option>
  <option value="991">Ужур</option>
  <option value="1010">Уяр</option>
  <option value="1063">Шарыпово</option>
  </optgroup>
  <optgroup label="Курганская обл">
  <option value="242">Далматово</option>
  <option value="428">Катайск</option>
  <option value="485">Курган</option>
  <option value="497">Куртамыш</option>
  <option value="561">Макушино</option>
  <option value="765">Петухово</option>
  <option value="1059">Шадринск</option>
  <option value="1074">Шумиха</option>
  <option value="1081">Щучье</option>
  </optgroup>
  <optgroup label="Курская обл">
  <option value="272">Дмитриев-Льговский</option>
  <option value="288">Железногорск</option>
  <option value="495">Курск</option>
  <option value="499">Курчатов</option>
  <option value="537">Льгов</option>
  <option value="696">Обоянь</option>
  <option value="813">Рыльск</option>
  <option value="900">Суджа</option>
  <option value="1011">Фатеж</option>
  <option value="1079">Щигры</option>
  </optgroup>
  <optgroup label="Ленинградская обл">
  <option value="829">Санкт-Петербург</option>
  <option value="96">Бокситогорск</option>
  <option value="85575">Военный</option>
  <option value="86529">Военный 1-й</option>
  <option value="158">Волосово</option>
  <option value="160">Волхов</option>
  <option value="176">Всеволожск</option>
  <option value="180">Выборг</option>
  <option value="186">Высоцк</option>
  <option value="212">Гатчина</option>
  <option value="88987">ГО-1</option>
  <option value="85487">Ермилово</option>
  <option value="303">Зеленогорск</option>
  <option value="331">Ивангород</option>
  <option value="378">Каменногорск</option>
  <option value="452">Кингисепп</option>
  <option value="466">Кириши</option>
  <option value="476">Кировск</option>
  <option value="365">Колпино</option>
  <option value="369">Коммунар</option>
  <option value="178533">Красное Село</option>
  <option value="459">Кронштадт</option>
  <option value="178498">Ленинград</option>
  <option value="87306">Лодейное Поле</option>
  <option value="519">Ломоносов</option>
  <option value="523">Луга</option>
  <option value="539">Любань</option>
  <option value="612">Никольское</option>
  <option value="85222">Новая Ладога</option>
  <option value="717">Отрадное</option>
  <option value="178536">Павловск</option>
  <option value="753">Петергоф</option>
  <option value="178538">Петродворец</option>
  <option value="773">Пикалево</option>
  <option value="789">Подпорожье</option>
  <option value="758">Приморск</option>
  <option value="762">Приозерск</option>
  <option value="782">Пушкин</option>
  <option value="855">Светогорск</option>
  <option value="903">Сертолово</option>
  <option value="905">Сестрорецк</option>
  <option value="921">Сланцы</option>
  <option value="84350">Сосновый Бор</option>
  <option value="932">Сясьстрой</option>
  <option value="973">Тихвин</option>
  <option value="948">Тосно</option>
  <option value="1070">Шлиссельбург</option>
  </optgroup>
  <optgroup label="Липецкая обл">
  <option value="213">Грязи</option>
  <option value="250">Данков</option>
  <option value="281">Елец</option>
  <option value="306">Задонск</option>
  <option value="524">Лебедянь</option>
  <option value="546">Липецк</option>
  <option value="984">Усмань</option>
  <option value="1037">Чаплыгин</option>
  </optgroup>
  <optgroup label="Магаданская обл">
  <option value="6">Магадан</option>
  <option value="916">Сусуман</option>
  </optgroup>
  <optgroup label="Марий Эл Респ">
  <option value="148">Волжск</option>
  <option value="328">Звенигово</option>
  <option value="351">Йошкар-Ола</option>
  <option value="355">Козьмодемьянск</option>
  </optgroup>
  <optgroup label="Мордовия Респ">
  <option value="30">Ардатов</option>
  <option value="332">Инсар</option>
  <option value="502">Ковылкино</option>
  <option value="443">Краснослободск</option>
  <option value="807">Рузаевка</option>
  <option value="831">Саранск</option>
  <option value="963">Темников</option>
  </optgroup>
  <optgroup label="Московская обл">
  <option value="3">Москва</option>
  <option value="22">Апрелевка</option>
  <option value="85">Балашиха</option>
  <option value="124">Бронницы</option>
  <option value="161">Верея</option>
  <option value="183">Видное</option>
  <option value="93875">Военный</option>
  <option value="156">Волоколамск</option>
  <option value="172">Воскресенск</option>
  <option value="184">Высоковск</option>
  <option value="93886">Гарнизон</option>
  <option value="95106">Голицыно</option>
  <option value="93887">Городок-Б</option>
  <option value="254">Дедовск</option>
  <option value="264">Дзержинский</option>
  <option value="239">Дмитров</option>
  <option value="91801">Дмитров-4</option>
  <option value="91802">Дмитров-5</option>
  <option value="247">Долгопрудный</option>
  <option value="251">Домодедово</option>
  <option value="259">Дрезна</option>
  <option value="261">Дубна</option>
  <option value="273">Егорьевск</option>
  <option value="294">Железнодорожный</option>
  <option value="96760">Жилгородок</option>
  <option value="297">Жуковский</option>
  <option value="320">Зарайск</option>
  <option value="330">Звенигород</option>
  <option value="305">Зеленоград</option>
  <option value="335">Ивантеевка</option>
  <option value="346">Истра</option>
  <option value="90924">Калининград</option>
  <option value="434">Кашира</option>
  <option value="488">Климовск</option>
  <option value="490">Клин</option>
  <option value="93279">Клин-9</option>
  <option value="96299">Коковино</option>
  <option value="361">Коломна</option>
  <option value="93431">Коломна-1</option>
  <option value="391">Королев</option>
  <option value="93889">Котельники</option>
  <option value="419">Красноармейск</option>
  <option value="425">Красногорск</option>
  <option value="431">Краснозаводск</option>
  <option value="90932">Краснознаменск</option>
  <option value="95107">Кубинка</option>
  <option value="493">Куровское</option>
  <option value="544">Ликино-Дулево</option>
  <option value="515">Лобня</option>
  <option value="521">Лосино-Петровский</option>
  <option value="529">Луховицы</option>
  <option value="535">Лыткарино</option>
  <option value="541">Люберцы</option>
  <option value="580">Можайск</option>
  <option value="608">Мытищи</option>
  <option value="629">Наро-Фоминск</option>
  <option value="98317">Новый</option>
  <option value="672">Ногинск</option>
  <option value="700">Одинцово</option>
  <option value="95086">Одинцово-1</option>
  <option value="95105">Одинцово-10</option>
  <option value="702">Ожерелье</option>
  <option value="708">Озеры</option>
  <option value="96291">Ольховка</option>
  <option value="697">Орехово-Зуево</option>
  <option value="95420">Павловский Посад</option>
  <option value="96613">Пересвет</option>
  <option value="787">Подольск</option>
  <option value="768">Протвино</option>
  <option value="784">Пушкино</option>
  <option value="786">Пущино</option>
  <option value="800">Раменское</option>
  <option value="808">Реутов</option>
  <option value="797">Рошаль</option>
  <option value="805">Руза</option>
  <option value="96615">Сергиев Посад</option>
  <option value="96535">Сергиев Посад-14</option>
  <option value="96536">Сергиев Посад-15</option>
  <option value="96537">Сергиев Посад-6</option>
  <option value="96538">Сергиев Посад-7</option>
  <option value="901">Серпухов</option>
  <option value="840">Солнечногорск</option>
  <option value="97131">Солнечногорск-2</option>
  <option value="97133">Солнечногорск-25</option>
  <option value="97134">Солнечногорск-30</option>
  <option value="97132">Солнечногорск-7</option>
  <option value="94837">Старая Купавна</option>
  <option value="896">Ступино</option>
  <option value="922">Сходня</option>
  <option value="941">Талдом</option>
  <option value="96301">Теряево</option>
  <option value="954">Троицк</option>
  <option value="1014">Фрязино</option>
  <option value="1022">Химки</option>
  <option value="1028">Хотьково</option>
  <option value="94836">Черноголовка</option>
  <option value="1042">Чехов</option>
  <option value="97772">Чехов-1</option>
  <option value="97768">Чехов-2</option>
  <option value="97769">Чехов-3</option>
  <option value="97773">Чехов-4</option>
  <option value="97775">Чехов-5</option>
  <option value="97776">Чехов-6</option>
  <option value="97770">Чехов-7</option>
  <option value="97771">Чехов-8</option>
  <option value="1067">Шатура</option>
  <option value="1080">Щелково</option>
  <option value="1077">Щербинка</option>
  <option value="1082">Электрогорск</option>
  <option value="1084">Электросталь</option>
  <option value="1086">Электроугли</option>
  <option value="1088">Юбилейный</option>
  <option value="1108">Яхрома</option>
  </optgroup>
  <optgroup label="Мурманская обл">
  <option value="20">Апатиты</option>
  <option value="206">Гаджиево</option>
  <option value="314">Заозерск</option>
  <option value="318">Заполярный</option>
  <option value="396">Кандалакша</option>
  <option value="98359">Кировск</option>
  <option value="498">Ковдор</option>
  <option value="357">Кола</option>
  <option value="586">Мончегорск</option>
  <option value="600">Мурманск</option>
  <option value="716">Оленегорск</option>
  <option value="713">Островной</option>
  <option value="98388">Полярные Зори</option>
  <option value="738">Полярный</option>
  <option value="871">Североморск</option>
  <option value="931">Снежногорск</option>
  </optgroup>
  <optgroup label="Ненецкий АО">
  <option value="633">Нарьян-Мар</option>
  </optgroup>
  <optgroup label="Нижегородская обл">
  <option value="34">Арзамас</option>
  <option value="83">Балахна</option>
  <option value="88">Богородск</option>
  <option value="110">Бор</option>
  <option value="181">Ветлуга</option>
  <option value="154">Володарск</option>
  <option value="170">Ворсма</option>
  <option value="182">Выкса</option>
  <option value="224">Горбатов</option>
  <option value="234">Городец</option>
  <option value="98535">Горький</option>
  <option value="262">Дзержинск</option>
  <option value="304">Заволжье</option>
  <option value="98822">Истомино</option>
  <option value="496">Княгинино</option>
  <option value="465">Кстово</option>
  <option value="477">Кулебаки</option>
  <option value="527">Лукоянов</option>
  <option value="531">Лысково</option>
  <option value="613">Навашино</option>
  <option value="98534">Нижний Новгород</option>
  <option value="727">Павлово</option>
  <option value="743">Первомайск</option>
  <option value="102128">Перевоз</option>
  <option value="837">Саров</option>
  <option value="887">Семенов</option>
  <option value="893">Сергач</option>
  <option value="1003">Урень</option>
  <option value="1048">Чкаловск</option>
  <option value="1073">Шахунья</option>
  </optgroup>
  <optgroup label="Новгородская обл">
  <option value="116">Боровичи</option>
  <option value="143">Валдай</option>
  <option value="104110">Великий Новгород</option>
  <option value="105858">Малая Вишера</option>
  <option value="714">Окуловка</option>
  <option value="751">Пестово</option>
  <option value="846">Сольцы</option>
  <option value="107152">Сольцы 2</option>
  <option value="107463">Старая Русса</option>
  <option value="1024">Холм</option>
  <option value="1050">Чудово</option>
  </optgroup>
  <optgroup label="Новосибирская обл">
  <option value="93">Барабинск</option>
  <option value="135">Бердск</option>
  <option value="102">Болотное</option>
  <option value="344">Искитим</option>
  <option value="406">Карасук</option>
  <option value="412">Каргат</option>
  <option value="475">Куйбышев</option>
  <option value="483">Купино</option>
  <option value="646">Новосибирск</option>
  <option value="698">Обь</option>
  <option value="953">Татарск</option>
  <option value="979">Тогучин</option>
  <option value="1051">Черепаново</option>
  <option value="1052">Чулым</option>
  <option value="109722">Чулым-3</option>
  </optgroup>
  <optgroup label="Омская обл">
  <option value="342">Исилькуль</option>
  <option value="362">Калачинск</option>
  <option value="623">Называевск</option>
  <option value="722">Омск</option>
  <option value="949">Тара</option>
  <option value="978">Тюкалинск</option>
  </optgroup>
  <optgroup label="Оренбургская обл">
  <option value="15">Абдулино</option>
  <option value="130">Бугуруслан</option>
  <option value="134">Бузулук</option>
  <option value="208">Гай</option>
  <option value="467">Кувандык</option>
  <option value="593">Медногорск</option>
  <option value="652">Новотроицк</option>
  <option value="695">Оренбург</option>
  <option value="701">Орск</option>
  <option value="842">Соль-Илецк</option>
  <option value="848">Сорочинск</option>
  <option value="1106">Ясный</option>
  </optgroup>
  <optgroup label="Орловская обл">
  <option value="106">Болхов</option>
  <option value="114587">Дмитровск</option>
  <option value="542">Ливны</option>
  <option value="569">Малоархангельск</option>
  <option value="604">Мценск</option>
  <option value="648">Новосиль</option>
  <option value="703">Орел</option>
  </optgroup>
  <optgroup label="Пензенская обл">
  <option value="101">Беднодемьяновск</option>
  <option value="113">Белинский</option>
  <option value="236">Городище</option>
  <option value="322">Заречный</option>
  <option value="376">Каменка</option>
  <option value="473">Кузнецк</option>
  <option value="117604">Кузнецк-12</option>
  <option value="117605">Кузнецк-8</option>
  <option value="117997">Нижний Ломов</option>
  <option value="118056">Никольск</option>
  <option value="741">Пенза</option>
  <option value="897">Сердобск</option>
  <option value="116921">Спасск</option>
  <option value="914">Сурск</option>
  </optgroup>
  <optgroup label="Пермский край">
  <option value="45">Александровск</option>
  <option value="137">Березники</option>
  <option value="159">Верещагино</option>
  <option value="228">Горнозаводск</option>
  <option value="209">Гремячинск</option>
  <option value="217">Губаха</option>
  <option value="245">Добрянка</option>
  <option value="442">Кизел</option>
  <option value="120641">Красновишерск</option>
  <option value="439">Краснокамск</option>
  <option value="471">Кудымкар</option>
  <option value="481">Кунгур</option>
  <option value="533">Лысьва</option>
  <option value="682">Нытва</option>
  <option value="705">Оса</option>
  <option value="723">Оханск</option>
  <option value="725">Очер</option>
  <option value="749">Пермь</option>
  <option value="838">Соликамск</option>
  <option value="986">Усолье</option>
  <option value="1033">Чайковский</option>
  <option value="1047">Чердынь</option>
  <option value="1032">Чермоз</option>
  <option value="1036">Чернушка</option>
  <option value="1054">Чусовой</option>
  </optgroup>
  <optgroup label="Приморский край">
  <option value="1">Владивосток</option>
  <option value="40">Арсеньев</option>
  <option value="1110">Артем</option>
  <option value="1111">Большой Камень</option>
  <option value="244">Дальнегорск</option>
  <option value="246">Дальнереченск</option>
  <option value="179911">Лазо</option>
  <option value="538">Лесозаводск</option>
  <option value="1114">Лучегорск</option>
  <option value="179916">Надеждинский р-н</option>
  <option value="2">Находка</option>
  <option value="737">Партизанск</option>
  <option value="179910">Преображение</option>
  <option value="870">Спасск-Дальний</option>
  <option value="179915">Тавричанка</option>
  <option value="990">Уссурийск</option>
  <option value="1013">Фокино</option>
  <option value="179914">Хороль</option>
  <option value="179917">Шкотовский р-н</option>
  </optgroup>
  <optgroup label="Псковская обл">
  <option value="123321">Великие Луки</option>
  <option value="216">Гдов</option>
  <option value="243">Дно</option>
  <option value="637">Невель</option>
  <option value="642">Новоржев</option>
  <option value="650">Новосокольники</option>
  <option value="693">Опочка</option>
  <option value="711">Остров</option>
  <option value="771">Печоры</option>
  <option value="742">Порхов</option>
  <option value="772">Псков</option>
  <option value="778">Пустошка</option>
  <option value="788">Пыталово</option>
  <option value="861">Себеж</option>
  </optgroup>
  <optgroup label="Ростовская обл">
  <option value="27">Азов</option>
  <option value="31">Аксай</option>
  <option value="99">Батайск</option>
  <option value="132955">Белая Калитва</option>
  <option value="144">Волгодонск</option>
  <option value="225">Гуково</option>
  <option value="253">Донецк</option>
  <option value="299">Зверево</option>
  <option value="313">Зерноград</option>
  <option value="382">Каменск-Шахтинский</option>
  <option value="381">Константиновск</option>
  <option value="133720">Красный Сулин</option>
  <option value="556">Миллерово</option>
  <option value="588">Морозовск</option>
  <option value="664">Новочеркасск</option>
  <option value="666">Новошахтинск</option>
  <option value="766">Пролетарск</option>
  <option value="795">Ростов-на-Дону</option>
  <option value="825">Сальск</option>
  <option value="883">Семикаракорск</option>
  <option value="935">Таганрог</option>
  <option value="1030">Цимлянск</option>
  <option value="1069">Шахты</option>
  </optgroup>
  <optgroup label="Рязанская обл">
  <option value="420">Касимов</option>
  <option value="385">Кораблино</option>
  <option value="568">Михайлов</option>
  <option value="636">Новомичуринск</option>
  <option value="811">Рыбное</option>
  <option value="815">Ряжск</option>
  <option value="817">Рязань</option>
  <option value="839">Сасово</option>
  <option value="913">Скопин</option>
  <option value="868">Спас-Клепики</option>
  <option value="872">Спасск-Рязанский</option>
  <option value="1075">Шацк</option>
  </optgroup>
  <optgroup label="Самарская обл">
  <option value="287">Жигулевск</option>
  <option value="454">Кинель</option>
  <option value="138865">Нефтегорск</option>
  <option value="634">Новокуйбышевск</option>
  <option value="710">Октябрьск</option>
  <option value="719">Отрадный</option>
  <option value="744">Похвистнево</option>
  <option value="827">Самара</option>
  <option value="924">Сызрань</option>
  <option value="934">Тольятти</option>
  <option value="1035">Чапаевск</option>
  </optgroup>
  <optgroup label="Саратовская обл">
  <option value="36">Аркадак</option>
  <option value="56">Аткарск</option>
  <option value="81">Балаково</option>
  <option value="87">Балашов</option>
  <option value="164">Вольск</option>
  <option value="280">Ершов</option>
  <option value="366">Калининск</option>
  <option value="139586">Красноармейск</option>
  <option value="140544">Красный Кут</option>
  <option value="583">Маркс</option>
  <option value="654">Новоузенск</option>
  <option value="757">Петровск</option>
  <option value="774">Пугачев</option>
  <option value="799">Ртищево</option>
  <option value="835">Саратов</option>
  <option value="1018">Хвалынск</option>
  <option value="1068">Шиханы</option>
  <option value="1085">Энгельс</option>
  </optgroup>
  <optgroup label="Саха /Якутия/ Респ">
  <option value="39">Алдан</option>
  <option value="653">Нерюнгри</option>
  <option value="720">Олекминск</option>
  <option value="1101">Якутск</option>
  </optgroup>
  <optgroup label="Сахалинская обл">
  <option value="141868">Александровск-Сахалинский</option>
  <option value="18">Анива</option>
  <option value="141660">Горнозаводск</option>
  <option value="249">Долинск</option>
  <option value="395">Корсаков</option>
  <option value="141758">Красногорск</option>
  <option value="489">Курильск</option>
  <option value="557">Макаров</option>
  <option value="639">Невельск</option>
  <option value="721">Оха</option>
  <option value="740">Поронайск</option>
  <option value="865">Северо-Курильск</option>
  <option value="936">Томари</option>
  <option value="983">Углегорск</option>
  <option value="1026">Холмск</option>
  <option value="1071">Шахтерск</option>
  <option value="5">Южно-Сахалинск</option>
  </optgroup>
  <optgroup label="Свердловская обл">
  <option value="35">Алапаевск</option>
  <option value="26">Арамиль</option>
  <option value="46">Артемовский</option>
  <option value="50">Асбест</option>
  <option value="141932">Березовский</option>
  <option value="84">Богданович</option>
  <option value="142315">Верхний Тагил</option>
  <option value="141955">Верхняя Пышма</option>
  <option value="142294">Верхняя Салда</option>
  <option value="142321">Верхняя Тура</option>
  <option value="175">Верхотурье</option>
  <option value="162">Волчанск</option>
  <option value="252">Дегтярск</option>
  <option value="277">Екатеринбург</option>
  <option value="141985">Заречный</option>
  <option value="337">Ивдель</option>
  <option value="338">Ирбит</option>
  <option value="380">Каменск-Уральский</option>
  <option value="392">Камышлов</option>
  <option value="416">Карпинск</option>
  <option value="430">Качканар</option>
  <option value="472">Кировград</option>
  <option value="445">Краснотурьинск</option>
  <option value="447">Красноуральск</option>
  <option value="449">Красноуфимск</option>
  <option value="503">Кушва</option>
  <option value="536">Лесной</option>
  <option value="143444">Михайловск</option>
  <option value="143439">Н-Серги-3</option>
  <option value="643">Невьянск</option>
  <option value="143440">Нижние Серги</option>
  <option value="142261">Нижний Тагил</option>
  <option value="142291">Нижняя Салда</option>
  <option value="142143">Нижняя Тура</option>
  <option value="143483">Новая Ляля</option>
  <option value="658">Новоуральск</option>
  <option value="745">Первоуральск</option>
  <option value="730">Полевской</option>
  <option value="804">Ревда</option>
  <option value="806">Реж</option>
  <option value="141871">Свердловск</option>
  <option value="142170">Свердловск-44</option>
  <option value="142132">Свердловск-45</option>
  <option value="873">Североуральск</option>
  <option value="899">Серов</option>
  <option value="876">Среднеуральск</option>
  <option value="142312">Сухой Лог</option>
  <option value="928">Сысерть</option>
  <option value="933">Тавда</option>
  <option value="943">Талица</option>
  <option value="970">Туринск</option>
  </optgroup>
  <optgroup label="Северная Осетия - Алания Респ">
  <option value="33">Алагир</option>
  <option value="32">Ардон</option>
  <option value="15254">Беслан</option>
  <option value="195">Владикавказ</option>
  <option value="268">Дигора</option>
  <option value="584">Моздок</option>
  </optgroup>
  <optgroup label="Смоленская обл">
  <option value="147">Велиж</option>
  <option value="196">Вязьма</option>
  <option value="204">Гагарин</option>
  <option value="256">Демидов</option>
  <option value="260">Десногорск</option>
  <option value="257">Дорогобуж</option>
  <option value="267">Духовщина</option>
  <option value="285">Ельня</option>
  <option value="748">Починок</option>
  <option value="814">Рославль</option>
  <option value="803">Рудня</option>
  <option value="843">Сафоново</option>
  <option value="927">Смоленск</option>
  <option value="930">Сычевка</option>
  <option value="1102">Ярцево</option>
  </optgroup>
  <optgroup label="Ставропольский край">
  <option value="80">Благодарный</option>
  <option value="132">Буденновск</option>
  <option value="220">Георгиевск</option>
  <option value="282">Ессентуки</option>
  <option value="286">Железноводск</option>
  <option value="311">Зеленокумск</option>
  <option value="345">Изобильный</option>
  <option value="336">Ипатово</option>
  <option value="486">Кисловодск</option>
  <option value="534">Лермонтов</option>
  <option value="32849">Минеральные Воды</option>
  <option value="572">Михайловск</option>
  <option value="641">Невинномысск</option>
  <option value="32875">Нефтекумск</option>
  <option value="618">Новоалександровск</option>
  <option value="640">Новопавловск</option>
  <option value="792">Пятигорск</option>
  <option value="851">Светлоград</option>
  <option value="880">Ставрополь</option>
  </optgroup>
  <optgroup label="Таймырский (Долгано-Ненецкий) АО">
  <option value="265">Дудинка</option>
  </optgroup>
  <optgroup label="Тамбовская обл">
  <option value="296">Жердевка</option>
  <option value="482">Кирсанов</option>
  <option value="413">Котовск</option>
  <option value="576">Мичуринск</option>
  <option value="590">Моршанск</option>
  <option value="802">Рассказово</option>
  <option value="947">Тамбов</option>
  <option value="981">Уварово</option>
  </optgroup>
  <optgroup label="Татарстан Респ">
  <option value="21">Агрыз</option>
  <option value="25">Азнакаево</option>
  <option value="55">Альметьевск</option>
  <option value="67">Бавлы</option>
  <option value="98">Болгар</option>
  <option value="128">Бугульма</option>
  <option value="136">Буинск</option>
  <option value="279">Елабуга</option>
  <option value="308">Заинск</option>
  <option value="309">Зеленодольск</option>
  <option value="354">Казань</option>
  <option value="17739">Лаишево</option>
  <option selected="selected" value="526">Лениногорск</option>
  <option value="573">Мамадыш</option>
  <option value="607">Менделеевск</option>
  <option value="609">Мензелинск</option>
  <option value="18892">Набережные Челны</option>
  <option value="669">Нижнекамск</option>
  <option value="680">Нурлат</option>
  <option value="969">Тетюши</option>
  <option value="1044">Чистополь</option>
  </optgroup>
  <optgroup label="Тверская обл">
  <option value="14">Андреаполь</option>
  <option value="103">Бежецк</option>
  <option value="131">Белый</option>
  <option value="100">Бологое</option>
  <option value="179">Весьегонск</option>
  <option value="153968">Вышний Волочек</option>
  <option value="154385">Западная Двина</option>
  <option value="327">Зубцов</option>
  <option value="152327">Калинин</option>
  <option value="372">Калязин</option>
  <option value="432">Кашин</option>
  <option value="450">Кимры</option>
  <option value="375">Конаково</option>
  <option value="156866">Красный Холм</option>
  <option value="469">Кувшиново</option>
  <option value="513">Лихославль</option>
  <option value="645">Нелидово</option>
  <option value="709">Осташков</option>
  <option value="810">Ржев</option>
  <option value="884">Старица</option>
  <option value="957">Тверь</option>
  <option value="944">Торжок</option>
  <option value="946">Торопец</option>
  <option value="989">Удомля</option>
  </optgroup>
  <optgroup label="Томская обл">
  <option value="52">Асино</option>
  <option value="436">Кедровый</option>
  <option value="363">Колпашево</option>
  <option value="875">Северск</option>
  <option value="892">Стрежевой</option>
  <option value="940">Томск</option>
  </optgroup>
  <optgroup label="Тульская обл">
  <option value="51">Алексин</option>
  <option value="133">Белев</option>
  <option value="86">Богородицк</option>
  <option value="104">Болохово</option>
  <option value="157">Венев</option>
  <option value="255">Донской</option>
  <option value="284">Ефремов</option>
  <option value="448">Кимовск</option>
  <option value="458">Киреевск</option>
  <option value="548">Липки</option>
  <option value="638">Новомосковск</option>
  <option value="779">Плавск</option>
  <option value="75378">Советск</option>
  <option value="834">Сокольники</option>
  <option value="898">Суворов</option>
  <option value="964">Тула</option>
  <option value="993">Узловая</option>
  <option value="1043">Чекалин</option>
  <option value="1078">Щекино</option>
  <option value="1104">Ясногорск</option>
  </optgroup>
  <optgroup label="Тыва Респ">
  <option value="29">Ак-Довурак</option>
  <option value="505">Кызыл</option>
  <option value="968">Туран</option>
  <option value="1031">Чадан</option>
  <option value="1057">Шагонар</option>
  </optgroup>
  <optgroup label="Тюменская обл">
  <option value="300">Заводоуковск</option>
  <option value="348">Ишим</option>
  <option value="977">Тобольск</option>
  <option value="980">Тюмень</option>
  <option value="1103">Ялуторовск</option>
  </optgroup>
  <optgroup label="Удмуртская Респ">
  <option value="174">Воткинск</option>
  <option value="222">Глазов</option>
  <option value="20883">Городок-67</option>
  <option value="341">Ижевск</option>
  <option value="374">Камбарка</option>
  <option value="582">Можга</option>
  <option value="833">Сарапул</option>
  </optgroup>
  <optgroup label="Ульяновская обл">
  <option value="97">Барыш</option>
  <option value="270">Димитровград</option>
  <option value="349">Инза</option>
  <option value="656">Новоульяновск</option>
  <option value="889">Сенгилей</option>
  <option value="997">Ульяновск</option>
  </optgroup>
  <optgroup label="Хабаровский край">
  <option value="57">Амурск</option>
  <option value="66">Бикин</option>
  <option value="192">Вяземский</option>
  <option value="33474">Комсомольск-31</option>
  <option value="371">Комсомольск-на-Амуре</option>
  <option value="687">Николаевск-на-Амуре</option>
  <option value="1112">Охотск</option>
  <option value="33413">Переяславка Вторая</option>
  <option value="1113">Советская Гавань</option>
  <option value="4">Хабаровск</option>
  <option value="33782">Хабаровск-43</option>
  </optgroup>
  <optgroup label="Хакасия Респ">
  <option value="11">Абаза</option>
  <option value="13">Абакан</option>
  <option value="845">Саяногорск</option>
  <option value="850">Сорск</option>
  <option value="1034">Черногорск</option>
  </optgroup>
  <optgroup label="Ханты-Мансийский АО - Югра АО">
  <option value="129">Белоярский</option>
  <option value="504">Когалым</option>
  <option value="520">Лангепас</option>
  <option value="547">Лянтор</option>
  <option value="589">Мегион</option>
  <option value="663">Нефтеюганск</option>
  <option value="667">Нижневартовск</option>
  <option value="686">Нягань</option>
  <option value="791">Покачи</option>
  <option value="790">Пыть-Ях</option>
  <option value="179377">Радужный</option>
  <option value="830">Советский</option>
  <option value="910">Сургут</option>
  <option value="1001">Урай</option>
  <option value="1021">Ханты-Мансийск</option>
  <option value="1090">Югорск</option>
  </optgroup>
  <optgroup label="Челябинская обл">
  <option value="169816">1 Военный</option>
  <option value="62">Аша</option>
  <option value="75">Бакал</option>
  <option value="163">Верхнеуральск</option>
  <option value="169769">Верхний Уфалей</option>
  <option value="274">Еманжелинск</option>
  <option value="319">Златоуст</option>
  <option value="402">Карабаш</option>
  <option value="418">Карталы</option>
  <option value="422">Касли</option>
  <option value="426">Катав-Ивановск</option>
  <option value="383">Копейск</option>
  <option value="389">Коркино</option>
  <option value="501">Куса</option>
  <option value="507">Кыштым</option>
  <option value="551">Магнитогорск</option>
  <option value="552">Миасс</option>
  <option value="562">Миньяр</option>
  <option value="688">Нязепетровск</option>
  <option value="169946">Озерск</option>
  <option value="781">Пласт</option>
  <option value="841">Сатка</option>
  <option value="909">Сим</option>
  <option value="929">Снежинск</option>
  <option value="958">Трехгорный</option>
  <option value="169982">Трехгорный-1</option>
  <option value="171090">Троицк</option>
  <option value="996">Усть-Катав</option>
  <option value="1039">Чебаркуль</option>
  <option value="1045">Челябинск</option>
  <option value="1098">Южноуральск</option>
  <option value="1095">Юрюзань</option>
  </optgroup>
  <optgroup label="Чеченская Респ">
  <option value="28">Аргун</option>
  <option value="211">Грозный</option>
  <option value="223">Гудермес</option>
  <option value="1061">Шали</option>
  </optgroup>
  <optgroup label="Читинская обл">
  <option value="89">Балей</option>
  <option value="112">Борзя</option>
  <option value="437">Краснокаменск</option>
  <option value="578">Могоча</option>
  <option value="651">Нерчинск</option>
  <option value="171939">Петровск-Забайкальский</option>
  <option value="878">Сретенск</option>
  <option value="1020">Хилок</option>
  <option value="1046">Чита</option>
  <option value="171374">Чита-47</option>
  <option value="1064">Шилка</option>
  </optgroup>
  <optgroup label="Чувашская Респ">
  <option value="37">Алатырь</option>
  <option value="394">Канаш</option>
  <option value="353">Козловка</option>
  <option value="24313">Мариинский Посад</option>
  <option value="662">Новочебоксарск</option>
  <option value="1029">Цивильск</option>
  <option value="1041">Чебоксары</option>
  <option value="1072">Шумерля</option>
  <option value="1099">Ядрин</option>
  </optgroup>
  <optgroup label="Чукотский АО">
  <option value="59">Анадырь</option>
  <option value="68">Билибино</option>
  <option value="739">Певек</option>
  </optgroup>
  <optgroup label="Ямало-Ненецкий АО">
  <option value="221">Губкинский</option>
  <option value="512">Лабытнанги</option>
  <option value="596">Муравленко</option>
  <option value="617">Надым</option>
  <option value="179798">Новый Уренгой</option>
  <option value="678">Ноябрьск</option>
  <option value="823">Салехард</option>
  <option value="179909">Тарко-Сале</option>
  </optgroup>
  <optgroup label="Ярославская обл">
  <option value="200">Гаврилов-Ям</option>
  <option value="248">Данилов</option>
  <option value="543">Любим</option>
  <option value="610">Мышкин</option>
  <option value="747">Переславль-Залесский</option>
  <option value="750">Пошехонье</option>
  <option value="818">Ростов</option>
  <option value="809">Рыбинск</option>
  <option value="972">Тутаев</option>
  <option value="985">Углич</option>
  <option value="1100">Ярославль</option>
  </optgroup>
  <optgroup label="Другое">
  <option value="47">Александровск-Сахали</option>
  <option value="42">Артём</option>
  <option value="105">БелаяКалитва</option>
  <option value="107">БелаяХолуница</option>
  <option value="108">БольшойКамень</option>
  <option value="149">ВеликиеЛуки</option>
  <option value="151">ВеликийНовгород</option>
  <option value="153">ВеликийУстюг</option>
  <option value="165">ВерхнийТагил</option>
  <option value="167">ВерхнийУфалей</option>
  <option value="169">ВерхняяПышма</option>
  <option value="171">ВерхняяСалда</option>
  <option value="173">ВерхняяТура</option>
  <option value="177">Верхоянск</option>
  <option value="185">Вилюйск</option>
  <option value="190">ВышнийВолочёк</option>
  <option value="198">ВятскиеПоляны</option>
  <option value="202">ГавриловПосад</option>
  <option value="205">ГорячийКлюч</option>
  <option value="240">ДагестанскиеОгни</option>
  <option value="241">Дмитровск-Орловский</option>
  <option value="292">Железногорск-Илимски</option>
  <option value="316">ЗападнаяДвина</option>
  <option value="453">КрасныйКут</option>
  <option value="455">КрасныйСулин</option>
  <option value="457">КрасныйХолм</option>
  <option value="532">Ленск</option>
  <option value="517">ЛодейноеПоле</option>
  <option value="563">МалаяВишера</option>
  <option value="581">МариинскийПосад</option>
  <option value="558">МинеральныеВоды</option>
  <option value="611">НабережныеЧелны</option>
  <option value="673">НижниеСерги</option>
  <option value="677">Нижний-Новгород</option>
  <option value="675">НижнийЛомов</option>
  <option value="679">НижнийТагил</option>
  <option value="681">НижняяСалда</option>
  <option value="683">НижняяТура</option>
  <option value="614">НоваяЛадога</option>
  <option value="616">НоваяЛяля</option>
  <option value="668">НовыйОскол</option>
  <option value="670">НовыйУренгой</option>
  <option value="684">Нюрба</option>
  <option value="733">ПавловскийПосад</option>
  <option value="755">ПетровВал</option>
  <option value="759">Петровск-Забайкальск</option>
  <option value="728">Покровск</option>
  <option value="736">ПолярныеЗори</option>
  <option value="863">Северо-Задонск</option>
  <option value="895">СергиевПосад</option>
  <option value="828">СоветскаяГавань</option>
  <option value="860">СосновыйБор</option>
  <option value="874">Среднеколымск</option>
  <option value="882">СтараяРусса</option>
  <option value="888">СтарыйОскол</option>
  <option value="920">СухойЛог</option>
  <option value="938">Томмот</option>
  <option value="987">Удачный</option>
  <option value="1007">Урус-Мартан</option>
  </optgroup>
</select>

<?
$code = trim(ob_get_clean());

$tmp = explode('<optgroup label="', $code);

unset($tmp[0]);

include('config.php');
include('lib/sql.php');

$SQL->qw('TRUNCATE TABLE `#regions`');
$SQL->qw('TRUNCATE TABLE `#cities`');

foreach($tmp as $v)
{
    list($region, $cities) = explode('">', $v, 2);
    
    $cities = trim(strip_tags($cities));
    
    echo '<h3>'.$region.'</h3>';
    
    $SQL->qw('INSERT INTO `#regions` SET `name` = ?',$region);
    
    $rid = $SQL->insert_id();
    
    $cities = explode("\n", $cities);
    
    foreach($cities as $k=>$v)
    {
        $cities[$k] = trim($v);
        $SQL->qw('INSERT INTO `#cities` SET `name`=?, `region` = ?', $cities[$k], $rid);
    }
    
    echo '<pre>',!print_r($cities),'</pre>';
}

?>